#!/bin/bash
source data/config.sh
echo "Downloading lastest stable release of yaru theme from fr.archive.ubuntu.com..."
wget "http://fr.archive.ubuntu.com/ubuntu/pool/main/y/yaru-theme/yaru-theme-gnome-shell_$YARU_THEME_VERSION.deb"
wget "http://fr.archive.ubuntu.com/ubuntu/pool/main/y/yaru-theme/yaru-theme-gtk_$YARU_THEME_VERSION.deb"
wget "http://fr.archive.ubuntu.com/ubuntu/pool/main/y/yaru-theme/yaru-theme-icon_$YARU_THEME_VERSION.deb"
wget "http://fr.archive.ubuntu.com/ubuntu/pool/main/y/yaru-theme/yaru-theme-sound_$YARU_THEME_VERSION.deb"
echo "Starting yaru-theme packages installation and configuration..."
sudo apt install ./yaru-theme-gnome-shell_$YARU_THEME_VERSION.deb ./yaru-theme-gtk_$YARU_THEME_VERSION.deb ./yaru-theme-icon_$YARU_THEME_VERSION.deb ./yaru-theme-sound_$YARU_THEME_VERSION.deb
sudo mv /usr/share/gnome-shell/theme/ubuntu.css /usr/share/gnome-shell/theme/ubuntu.css.bak
sudo mv /usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/stylesheet.css /usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/stylesheet.css.bak
sudo mv /usr/share/gnome-shell/modes/ubuntu.json /usr/share/gnome-shell/modes/ubuntu.json.bak
sudo mv /usr/share/gnome-shell/theme/ubuntu-high-contrast.css /usr/share/gnome-shell/theme/ubuntu-high-contrast.css.bak
sudo ln -s /usr/share/gnome-shell/theme/Yaru/gnome-shell.css /usr/share/gnome-shell/theme/ubuntu.css
sudo ln -s /usr/share/gnome-shell/theme/Yaru/gnome-shell-high-contrast.css /usr/share/gnome-shell/theme/ubuntu-high-contrast.css
sudo ln -s /usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/yaru.css /usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/stylesheet.css
sudo ln -s /usr/share/gnome-shell/modes/yaru.json /usr/share/gnome-shell/modes/ubuntu.json
sudo cp data/yaru.css /usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/yaru.css
gsettings set org.gnome.desktop.interface cursor-theme 'Yaru'
gsettings set org.gnome.desktop.interface icon-theme 'Yaru'
gsettings set org.gnome.desktop.interface gtk-theme 'Yaru'
gsettings set org.gnome.desktop.sound theme-name 'Yaru'
echo "Removing deb packages..."
rm "yaru-theme-gnome-shell_$YARU_THEME_VERSION.deb"
rm "yaru-theme-gtk_$YARU_THEME_VERSION.deb"
rm "yaru-theme-icon_$YARU_THEME_VERSION.deb"
rm "yaru-theme-sound_$YARU_THEME_VERSION.deb"
echo "Gnome Shell is restarting... Please wait."
gnome-shell --replace&
