#!/bin/bash
echo "Rollbacking configurations..."
sudo rm -rf /usr/share/gnome-shell/theme/ubuntu.css
sudo rm -rf /usr/share/gnome-shell/theme/ubuntu-high-contrast.css
sudo rm -rf /usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/stylesheet.css
sudo rm -rf /usr/share/gnome-shell/modes/ubuntu.json
sudo mv /usr/share/gnome-shell/theme/ubuntu.css.bak /usr/share/gnome-shell/theme/ubuntu.css
sudo mv /usr/share/gnome-shell/theme/ubuntu-high-contrast.css.bak /usr/share/gnome-shell/theme/ubuntu-high-contrast.css
sudo mv /usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/stylesheet.css.bak /usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/stylesheet.css
sudo mv /usr/share/gnome-shell/modes/ubuntu.json.bak /usr/share/gnome-shell/modes/ubuntu.json
gsettings reset org.gnome.desktop.interface cursor-theme
gsettings reset org.gnome.desktop.interface icon-theme
gsettings reset org.gnome.desktop.interface gtk-theme
gsettings reset org.gnome.desktop.sound theme-name
echo "Removing yaru-theme packages..."
sudo apt remove yaru-theme-gnome-shell yaru-theme-gtk yaru-theme-icon yaru-theme-sound --purge
echo "Gnome Shell is restarting... Please wait."
gnome-shell --replace&
